#include <stdio.h>
#include <stdlib.h>
#include <gmp.h>
#define num_of_features 100
#define C 2
#define epsilon 2
#define eta (num_of_features + 1 + C + epsilon)

mpz_t decrypted_query[eta];

mpz_t betaQ;

void printBetaGenByDO()
{
    FILE *file;
    file = fopen("BetaGeneratedByDO.txt", "r");
    mpz_init(betaQ);
    gmp_fscanf(file, "%Zd ", betaQ);
    gmp_printf("%s = %Zd\n", "Beta generated by DO = ", betaQ);
    fclose(file);
}

void readDecryptedQuery()
{
    FILE *file;
    file = fopen("finalDecryptedQuery.txt", "r");
    for (int i = 0; i < eta; i++)
    {
        mpz_init(decrypted_query[i]);
        gmp_fscanf(file, "%Zd ", decrypted_query[i]);
    }
    fclose(file);
}

void calcBeta()
{
    mpz_t gcd;
    mpz_init_set(gcd, decrypted_query[0]);
    for (int i = 1; i < eta; i++)
    {
        mpz_gcd(gcd, gcd, decrypted_query[i]);
    }
    gmp_printf("%s = %Zd\n", "Calculated Beta at QU = ", gcd);
    mpz_clear(gcd);
}

void garbageCollection()
{
    mpz_clear(betaQ);
    for (int i = 0; i < eta; i++)
    {
        mpz_clear(decrypted_query[i]);
    }
}

int main()
{
    printBetaGenByDO();
    readDecryptedQuery();
    calcBeta();

    garbageCollection();
    return 0;
}
